[package]
name = "rakh"
version = "0.1.0"
edition = "2021"
description = "A dead simple configuration language."
license = "Blue Oak 1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
